spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-79-125-26-232.eu-west-1.compute.amazonaws.com:5432/da69iiqgavtliq?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: oimdgdyotuhmgu
    password: 7583b686a2b0e3ad13019629fc227b4219bdf9b2f2e687aaab91dda2f7be89ce
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  vaadin:
    productionMode: false
    compatibilityMode: true

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 591a7ab726eb60dbc5eb
            clientSecret: d4fb9a2ea8179838e40b076922b96a6b58fd8ba2
          google:
            clientId: 761742879560-ch093e94rj6gq9kpo4tsu224cnni7j4e.apps.googleusercontent.com
            clientSecret: 4WtuIcrwu_jCmeg2T8xGEPYg