spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delegation?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: JebacDisa69@
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  vaadin:
    productionMode: false
    compatibilityMode: true

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 591a7ab726eb60dbc5eb
            clientSecret: d4fb9a2ea8179838e40b076922b96a6b58fd8ba2
          google:
            clientId: 761742879560-ch093e94rj6gq9kpo4tsu224cnni7j4e.apps.googleusercontent.com
            clientSecret: 4WtuIcrwu_jCmeg2T8xGEPYg